### ISSUE TITLE
No whitespace?

### ISSUE THREAD

**Issue by harisont** [JuanJakobo/PB-Read-offline#2]
Hey!
Great to see this. I tried to implement the same thing myself but couldn't figure out how to use the runtime properly.
I'm having a weird issue, though. When I try to read articles, there are no spaces between words. Do you have the same problem?

**Comment by JuanJakobo** [comment]
Hey, 
I had the same issue on the newest release of the PB software with the integrated reader. I created a bug report for it, but nobody seems to care. 
Since this happened I use [Koreader](https://github.com/koreader/koreader) and it works like a charm (no white space issue).
I adapted the Koreader config so that all .html files are automatically opened by it. Furthermore you can change the config of it, so that by a clicking of the bottom left the document is closed. So if the document is opened by the App it will automatically resume to it.

**Comment by harisont** [comment]
Thanks for the tip! It seems like a great reader in general, too

**Comment by JuanJakobo** [comment]
Just for your info, I upgraded to U632.6.5.2919 a minute ago and it seems as if this update fixes the white space error also for the internal reader. :)

**Comment by harisont** [comment]
Yep, I noticed! But thank you for telling me anyway :)
